import carList from "./assets/carList.png";

export const cars = [
  {
    id: "d2a63a8e-2146-4c8e-8eef-36a3d7c3e530",
    mark: "chevrolet",
    model: "prisma",
    year: 2021,
    mileage: "55555",
    color: "azul",
    priceFipe: 85100,
    price: 90500,
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus ut, corrupti dignissimos Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, sunt. Aliquam vero voluptatum earum, consequuntur odit corrupti recusandae nemo optio quaerat ea eos laboriosam qui nobis quam aperiam? Atque, quas.",
    imgCover: carList,
    isActive: true,
    advertiser: "Paulo Rodrigues",
  },
  {
    id: "4de2c052-14f4-46fe-9b1a-2dc93d2fe7e1",
    mark: "ford",
    model: "mustang",
    year: 2019,
    mileage: "25000",
    color: "vermelho",
    priceFipe: 100000,
    price: 95000,
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus ut, corrupti dignissimos Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, sunt. Aliquam vero voluptatum earum, consequuntur odit corrupti recusandae nemo optio quaerat ea eos laboriosam qui nobis quam aperiam? Atque, quas.",
    imgCover: carList,
    isActive: true,
    advertiser: "Roberto Carlos",
  },
  {
    id: "9f8a3b58-3a4b-4854-a738-c8650f8c3033",
    mark: "volkswagen",
    model: "golf",
    year: 2017,
    mileage: "40000",
    color: "preto",
    priceFipe: 60000,
    price: 55000,
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus ut, corrupti dignissimos Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, sunt. Aliquam vero voluptatum earum, consequuntur odit corrupti recusandae nemo optio quaerat ea eos laboriosam qui nobis quam aperiam? Atque, quas.",
    imgCover: carList,
    isActive: true,
    advertiser: "Jorge Lafond",
  },
  {
    id: "d2a63a8e-2146-4c8e-8eef-36a3d7c3e530",
    mark: "chevrolet",
    model: "prisma",
    year: 2021,
    mileage: "55555",
    color: "azul",
    priceFipe: 85100,
    price: 90500,
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus ut, corrupti dignissimos Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, sunt. Aliquam vero voluptatum earum, consequuntur odit corrupti recusandae nemo optio quaerat ea eos laboriosam qui nobis quam aperiam? Atque, quas.",
    imgCover: carList,
    isActive: true,
    advertiser: "Paulo Rodrigues",
  },
  {
    id: "4de2c052-14f4-46fe-9b1a-2dc93d2fe7e1",
    mark: "ford",
    model: "mustang",
    year: 2019,
    mileage: "25000",
    color: "vermelho",
    priceFipe: 100000,
    price: 95000,
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus ut, corrupti dignissimos Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, sunt. Aliquam vero voluptatum earum, consequuntur odit corrupti recusandae nemo optio quaerat ea eos laboriosam qui nobis quam aperiam? Atque, quas.",
    imgCover: carList,
    isActive: true,
    advertiser: "Roberto Carlos",
  },
  {
    id: "9f8a3b58-3a4b-4854-a738-c8650f8c3033",
    mark: "volkswagen",
    model: "golf",
    year: 2017,
    mileage: "40000",
    color: "preto",
    priceFipe: 60000,
    price: 55000,
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus ut, corrupti dignissimos Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, sunt. Aliquam vero voluptatum earum, consequuntur odit corrupti recusandae nemo optio quaerat ea eos laboriosam qui nobis quam aperiam? Atque, quas.",
    imgCover: carList,
    isActive: true,
    advertiser: "Jorge Lafond",
  },
];
